### ISSUE TITLE
[Feature Request] Migrate Frontend to PatternFly

### ISSUE THREAD

**Issue by ericpritchett** [RobinBeismann/scupPS#24]
PatternFly is under the MIT license and I think would offer an easier and more consistent way to build a frontend with Pode.  "PatternFly is an open source design system created to enable consistency and usability across a wide range of applications and use cases. PatternFly provides clear standards, guidance, and tools that help designers and developers work together more efficiently and build better user experiences."

PatternFly is what www.cockpit-project.org uses as well as some other open source projects and I think it would work here as well. Many of the components are already built for you and can be extended. For example, a login page https://www.patternfly.org/v4/documentation/react/components/loginpage or a table column manger demo that could be repurposed to see requests or something https://www.patternfly.org/v4/documentation/react/demos/tablecolumnmanagementdemo# . They have examples in both React and HTML/CSS.

More info:
- Website: https://www.patternfly.org/
- Documentation: https://www.patternfly.org/v4/documentation/react/overview/release-notes
- Design Guidelines: https://www.patternfly.org/v4/design-guidelines/styles/colors
- GitHub: https://github.com/patternfly/patternfly

**Comment by RobinBeismann** [comment]
Hi Eric,

thanks for asking, I'll make sure to review PatternFly after my vacation.
I used AdminLTE as it is a extension to bootstrap which is kinda a webstandard now a days and as it was easy to implement.

Are you using scupPS actually? I could think of supporting multiple designs, but I didn't really have time in the last month to improve scupPS in general, I only fixed bugs which we stumbled upon in my company.
